#!/usr/bin/env bash
set -euo pipefail

# Controller-lite worker for the M01 RDMA lab.
#
# It processes queued request files generated by testops-ci-submit.sh, takes a
# single lab lock, runs scripts/run-rdma-ci.sh, and moves each request to done or
# failed. This is deliberately boring: systemd can run it as a service, cron can
# run it periodically, and the dashboard remains read-only over result bundles.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

QUEUE_DIR="${TESTOPS_QUEUE_DIR:-/mnt/smb/work/share/testops/queue/rdma-ci}"
STATE_DIR="${TESTOPS_STATE_DIR:-/mnt/smb/work/share/testops/state/rdma-ci}"
LOCK_FILE="${TESTOPS_LOCK_FILE:-/mnt/smb/work/share/testops/locks/rdma-lab.lock}"
LOG_DIR="${TESTOPS_LOG_DIR:-/mnt/smb/work/share/testops/logs/rdma-ci}"
STATUS_DIR="${TESTOPS_STATUS_DIR:-${STATE_DIR}/status}"
POLL_SECONDS="${TESTOPS_POLL_SECONDS:-10}"
ONCE="${TESTOPS_ONCE:-false}"
RUN_SCRIPT="${TESTOPS_RDMA_CI_SCRIPT:-./scripts/run-rdma-ci.sh}"
DASHBOARD_URL="${TESTOPS_DASHBOARD_URL:-http://192.168.1.181:9099/}"
NOTIFY_EMAIL="${TESTOPS_NOTIFY_EMAIL:-}"
NOTIFY_CMD="${TESTOPS_NOTIFY_CMD:-}"

mkdir -p "$QUEUE_DIR" "$STATE_DIR"/{running,done,failed} "$STATUS_DIR" "$(dirname "$LOCK_FILE")" "$LOG_DIR"

have_flock=false
if command -v flock >/dev/null 2>&1; then
  have_flock=true
fi

write_status() {
  local request_id="$1"
  local state="$2"
  local exit_code="$3"
  local started_at="$4"
  local ended_at="$5"
  local log_path="$6"
  local bundle_dir="$7"
  local out="${STATUS_DIR}/${request_id}.json"

  REQUEST_ID="$request_id" \
  REQUEST_STATE="$state" \
  REQUEST_EXIT_CODE="$exit_code" \
  REQUEST_STARTED_AT="$started_at" \
  REQUEST_ENDED_AT="$ended_at" \
  REQUEST_LOG_PATH="$log_path" \
  REQUEST_BUNDLE_DIR="$bundle_dir" \
  REQUEST_DASHBOARD_URL="$DASHBOARD_URL" \
  python3 - "$out" "$STATUS_DIR/last-run.json" <<'PY'
import json
import os
import pathlib
import sys

out = pathlib.Path(sys.argv[1])
latest = pathlib.Path(sys.argv[2])

def env(name):
    return os.environ.get(name, "")

doc = {
    "request_id": env("REQUEST_ID"),
    "state": env("REQUEST_STATE"),
    "exit_code": int(env("REQUEST_EXIT_CODE") or "0"),
    "started_at": env("REQUEST_STARTED_AT"),
    "ended_at": env("REQUEST_ENDED_AT"),
    "mono_ref": env("TESTOPS_MONO_REF"),
    "mono_repo": env("TESTOPS_MONO_REPO"),
    "run_by": env("TESTOPS_RUN_BY"),
    "team": env("TESTOPS_TEAM"),
    "project": env("TESTOPS_PROJECT"),
    "test_id": env("TESTOPS_TEST_ID"),
    "branch": env("TESTOPS_BRANCH"),
    "commit": env("TESTOPS_COMMIT"),
    "log_path": env("REQUEST_LOG_PATH"),
    "bundle_dir": env("REQUEST_BUNDLE_DIR"),
    "dashboard_url": env("REQUEST_DASHBOARD_URL"),
}
out.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n")
latest.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n")
PY
}

notify_result() {
  local request_id="$1"
  local state="$2"
  local exit_code="$3"
  local log_path="$4"
  local bundle_dir="$5"
  local subject="[TestOps RDMA] ${state}: ${TESTOPS_MONO_REF:-unknown}"
  local body
  body=$(
    cat <<EOF
request_id: ${request_id}
state: ${state}
exit_code: ${exit_code}
mono_ref: ${TESTOPS_MONO_REF:-}
run_by: ${TESTOPS_RUN_BY:-}
log: ${log_path}
bundle: ${bundle_dir}
dashboard: ${DASHBOARD_URL}
EOF
  )

  TESTOPS_NOTIFY_STATE="$state" \
  TESTOPS_NOTIFY_EXIT_CODE="$exit_code" \
  TESTOPS_NOTIFY_REQUEST_ID="$request_id" \
  TESTOPS_NOTIFY_LOG="$log_path" \
  TESTOPS_NOTIFY_BUNDLE="$bundle_dir" \
  TESTOPS_NOTIFY_SUBJECT="$subject" \
  TESTOPS_NOTIFY_BODY="$body" \
  bash -lc "$NOTIFY_CMD" 2>/dev/null || true

  if [[ -n "$NOTIFY_EMAIL" ]] && command -v mail >/dev/null 2>&1; then
    printf '%s\n' "$body" | mail -s "$subject" "$NOTIFY_EMAIL" || true
  fi
}

run_request() {
  local req="$1"
  local base
  base="$(basename "$req" .env)"
  local running="${STATE_DIR}/running/${base}.env"
  local done="${STATE_DIR}/done/${base}.env"
  local failed="${STATE_DIR}/failed/${base}.env"
  local log="${LOG_DIR}/${base}.log"
  local started_at
  started_at="$(date -Is)"

  if ! mv "$req" "$running" 2>/dev/null; then
    return 0
  fi

  echo "[$started_at] starting $base" | tee -a "$log"
  set +u
  # shellcheck disable=SC1090
  source "$running"
  set -u
  export TESTOPS_MONO_REF="${TESTOPS_MONO_REF:-}"
  export TESTOPS_MONO_REPO="${TESTOPS_MONO_REPO:-}"
  export TESTOPS_RUN_BY="${TESTOPS_RUN_BY:-}"
  export TESTOPS_TEAM="${TESTOPS_TEAM:-}"
  export TESTOPS_PROJECT="${TESTOPS_PROJECT:-}"
  export TESTOPS_TEST_ID="${TESTOPS_TEST_ID:-}"
  export TESTOPS_BRANCH="${TESTOPS_BRANCH:-}"
  export TESTOPS_COMMIT="${TESTOPS_COMMIT:-}"
  write_status "$base" "running" 0 "$started_at" "" "$log" ""

  local status=0
  (
    "$RUN_SCRIPT"
  ) >>"$log" 2>&1 || status=$?
  local ended_at
  local bundle_dir
  ended_at="$(date -Is)"
  bundle_dir="$(sed -n 's/.*bundle: //p' "$log" | tail -n 1 | tr -d '\r')"

  if [[ "$status" -eq 0 ]]; then
    mv "$running" "$done"
    write_status "$base" "pass" "$status" "$started_at" "$ended_at" "$log" "$bundle_dir"
    notify_result "$base" "pass" "$status" "$log" "$bundle_dir"
    echo "[$ended_at] pass $base" | tee -a "$log"
  else
    mv "$running" "$failed"
    write_status "$base" "fail" "$status" "$started_at" "$ended_at" "$log" "$bundle_dir"
    notify_result "$base" "fail" "$status" "$log" "$bundle_dir"
    echo "[$ended_at] fail $base status=$status" | tee -a "$log"
  fi
  return "$status"
}

process_once() {
  local req
  req="$(find "$QUEUE_DIR" -maxdepth 1 -type f -name '*.env' | sort | head -n 1)"
  if [[ -z "$req" ]]; then
    return 0
  fi

  if [[ "$have_flock" == true ]]; then
    (
      flock 9
      run_request "$req"
    ) 9>"$LOCK_FILE"
  else
    mkdir "${LOCK_FILE}.dir" 2>/dev/null || {
      echo "lab lock busy: ${LOCK_FILE}.dir"
      return 0
    }
    trap 'rmdir "${LOCK_FILE}.dir" 2>/dev/null || true' RETURN
    run_request "$req"
  fi
}

if [[ "${1:-}" == "--once" ]]; then
  ONCE=true
fi

while true; do
  process_once || true
  if [[ "$ONCE" == true ]]; then
    break
  fi
  sleep "$POLL_SECONDS"
done
